services:
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar
    ports:
      - "6650:6650"
      - "8081:8080"
    command: ["/pulsar/bin/pulsar", "standalone"]

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension